version: '3.8'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7.2.1-alpine
    restart: always
    container_name: 'ichat_bot_redis'
    ports:
      - 6380:6380
    volumes:
      - redis_data:/redis/data

  postgres:
    container_name: 'ichat_bot_main_db'
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/postgresql/data

volumes:
  redis_data:
  postgres_data: