services:
  main_db:
    container_name: 'ichat_bot_main_db'
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST_LOCAL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_URL_LOCAL}
    ports:
      - 5432:5432
    volumes:
      - main_db:/var/lib/postgresql/data
  redis:
    image: redis:7.2.1-alpine
    container_name: 'ichat_bot_redis'
    ports:
      - 6380:6379
volumes:
  main_db:
  redis:
